# Generated by Django 4.2.2 on 2024-07-28 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0002_employee_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='status',
            new_name='active',
        ),
    ]
