# Generated by Django 4.2.2 on 2024-07-28 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0004_alter_employee_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='active',
            field=models.BooleanField(null=True),
        ),
    ]
